// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElPropper: typeof import('element-plus/es')['ElPropper']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ListBox: typeof import('./src/components/ListBox/ListBox.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal/LoginModal.vue')['default']
    MusicItem: typeof import('./src/components/MusicItem/MusicItem.vue')['default']
    MusicListDetail: typeof import('./src/components/MusicListDetail/MusicListDetail.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer/MusicPlayer.vue')['default']
    PlayList: typeof import('./src/components/PlayList/PlayList.vue')['default']
    RecommendMusicList: typeof import('./src/components/RecommendMuiscList/RecommendMusicList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideBar: typeof import('./src/components/SlideBar/SlideBar.vue')['default']
    UserModal: typeof import('./src/components/UserProfile/UserModal.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile/UserProfile.vue')['default']
  }
}
